FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY scripts/deployment/start_api.py .
COPY run_metadata.json .
COPY data/reference/reference_data.csv ./data/reference/

RUN mkdir -p notebooks/mlruns reports data

EXPOSE 8000

CMD ["python", "start_api.py"]
